<?php

namespace App\Presenters\Roles;

use App\Presenters\CoreGridPresenter;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Role;

class RoleGridPresenter extends CoreGridPresenter
{
    protected function setColumns()
    {
        return [
            [
                'key' => 'level',
                'filtering' => true,
            ],
            [
                'key' => 'name',
                'filtering' => true,
            ],
            [
                'key' => 'role_rank',
                'filtering' => true,
            ],
            [
                'key' => 'role_setting',
                'label' => __('role.fields.role_setting'),
                'cell' => 'roles.permission'
            ]
        ];
    }

    protected function customItemData($item)
    {
        $item['userLoginRoleRank'] = Auth::user()->roles()->min('role_rank');
        return $item;
    }

    protected function visibleDelete($item)
    {
        return $item->role_rank >= $item['userLoginRoleRank'] && (Role::find($item->id)->users()->count() == 0) && parent::visibleDelete($item);
    }

    protected function visibleEdit($item)
    {
        return $item->role_rank >= $item['userLoginRoleRank'] && parent::visibleEdit($item); // TODO: Change the autogenerated stub
    }
}
