<?php

namespace Modules\SystemManager\Grids\Users;

use Modules\Common\Grids\BaseGrid;

class UserGrid extends BaseGrid
{
    /**
     * The name of the grid
     *
     * @var string
     */
    protected $name = 'User';

    /**
    * Set the columns to be displayed.
    *
    * @return void
    * @throws \Exception if an error occurs during parsing of the data
    */
    public function setColumns()
    {
        return [
            [
                'key' => 'name',
                'filtering' => true,
            ], [
                'key' => 'email',
                'filtering' => true,
            ], [
                'key' => 'phone',
                'filtering' => true,
            ],
            [
                'key' => 'roles',
                'sortable' => false,
                'cell' => function ($item) {
                    $html = '';
                    foreach ($item['roles'] as $role) {
                        $html .= '<span class="badge badge-primary mr-2">' . $role . '</span>';
                    }
                    return $html;
                }
            ],
            'address'
        ];
    }

    protected function customItemData($item)
    {
        $item['roles'] = $item->roles()->pluck('name');
        $item['role_rank'] = $item->roles()->min('role_rank');
        return $item;
    }

    protected function visibleEdit($item)
    {
        if (user_get()->is_user_sa) {
            return $item->role_rank >= user_get()->highest_role && parent::visibleEdit($item);
        } else {
            return $item->status != 1 && $item->role_rank >= user_get()->highest_role && parent::visibleEdit($item);
        }
        // TODO: Change the autogenerated stub
    }

    protected function visibleDelete($item)
    {
        if (user_get()->is_user_sa) {
            return $item->role_rank >= user_get()->highest_role && parent::visibleEdit($item);
        } else {
            return $item->status != 1 && $item->role_rank >= user_get()->highest_role && parent::visibleEdit($item);
        }
    }
}
